name: Build Padavan Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget curl unzip gcc g++ cmake fakeroot libtool libtool-bin gperf gawk flex bison nano xxd \
            autoconf automake libncurses5-dev libncursesw5-dev zlib1g-dev python3-docutils gettext texinfo help2man

      - name: Clone padavan-ng source
        run: |
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git padavan
          cd padavan/toolchain-mipsel
          ./dl_toolchain.sh

      - name: Customize config
        run: |
          cd padavan/trunk
          fakeroot ./clear_tree.sh
          cp -rf configs/templates/config.RT-N56U .config

      - name: Build firmware
        run: |
          cd padavan/trunk
          fakeroot ./build_firmware.sh RT-N56U

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: padavan-firmware
          path: padavan/trunk/images/*.trx
